version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: estoque-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: estoque
      POSTGRES_PASSWORD: estoque123
      POSTGRES_DB: estoque-compras
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
